DROP TABLE IF EXISTS tokens;
DROP TABLE IF EXISTS events;
DROP TABLE IF EXISTS auths;
DROP TABLE IF EXISTS otps;
DROP TABLE IF EXISTS wallets;
DROP TABLE IF EXISTS wallet_histories;
DROP TABLE IF EXISTS bank_accounts;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS businesses;

DROP TYPE IF EXISTS ACCOUNT_TYPE_ENUM;
DROP TYPE IF EXISTS EVENT_ENVIRONMENT_ENUM;
DROP TYPE IF EXISTS EVENT_TYPE_ENUM;
DROP TYPE IF EXISTS TOKEN_TYPE_ENUM;
DROP TYPE IF EXISTS OTP_TYPE;
DROP TYPE IF EXISTS MODEL_STATUS_ENUM;
DROP TYPE IF EXISTS WITHDRAWAL_TYPE_ENUM;